//! Strategy SDK: write one Rust file, get a runnable, reportable strategy.
//!
//! Files placed in `src/strategies/user/` are discovered at build time (see
//! `build.rs`). Each must expose `pub fn entry() -> StrategyEntry`.

pub mod indicators;
pub mod manifest;
pub mod runner;
pub mod strategy;

use anyhow::{Context, Result};

pub use manifest::{Manifest, Param, ParamKind, Params};
pub use strategy::{Bar, Ctx, Exec, Fill, LimitOrder, Position, Size, Strategy, StrategyEntry};

/// Everything a strategy file normally needs.
pub mod prelude {
    pub use crate::event_engine::{Side, TimeExit};
    pub use crate::indicators::{Adx, Ewma, RollingMean};
    pub use crate::sdk::indicators::{
        Atr, Bollinger, Crossover, Ema, RollingHigh, RollingLow, Rsi, Sma, Vwap,
    };
    pub use crate::sdk::manifest::{Manifest, Param, Params};
    pub use crate::sdk::strategy::{
        Bar, Ctx, Exec, Fill, LimitOrder, Position, Size, Strategy, StrategyEntry,
    };
    pub use anyhow::{Result, bail, ensure};
    pub use chrono::{NaiveDate, NaiveTime};
}

// Generated by build.rs: `pub mod user { ... }` and `fn user_entries()`.
include!(concat!(env!("OUT_DIR"), "/user_strategies.rs"));

/// Every strategy compiled into this engine.
pub fn registry() -> Vec<StrategyEntry> {
    user_entries()
}

/// Look up a strategy by manifest id.
pub fn find(id: &str) -> Result<StrategyEntry> {
    registry()
        .into_iter()
        .find(|entry| entry.manifest.id == id)
        .with_context(|| format!("no SDK strategy with id {id:?} is compiled into this engine"))
}

/// Manifests of every compiled strategy as JSON, for the local UI.
pub fn manifests_json() -> Result<String> {
    let manifests = registry()
        .into_iter()
        .map(|entry| entry.manifest)
        .collect::<Vec<_>>();
    for manifest in &manifests {
        manifest.validate()?;
    }
    Ok(serde_json::to_string_pretty(&manifests)?)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn every_compiled_manifest_is_valid_and_unique() {
        let entries = registry();
        let mut ids = std::collections::HashSet::new();
        for entry in &entries {
            entry.manifest.validate().expect("valid manifest");
            assert!(ids.insert(entry.manifest.id.clone()), "duplicate id");
        }
        assert!(find("rsi_mean_reversion").is_ok());
    }
}
